#
# Copyright (c) 2023-2024 Edgeburn Media. All rights reserved.
#

# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=26.1
loader_version=0.19.3
loom_version=1.17.1
# Mod Properties
mod_version=1.2-26.1
maven_group=com.edgeburnmedia
archives_base_name=batterystatusinfo
# Dependencies
# check this on https://fabricmc.net/develop/
fabric_version=0.145.1+26.1
modmenu_version=18.0.0
cloth_config_version=26.1.154
oshi_version=6.6.2
